import { useState } from 'react'
import { Github, Linkedin, Mail, MapPin, Send } from 'lucide-react'
import SectionTitle from '../components/SectionTitle'
import PageMeta from '../components/PageMeta'
import { personal } from '../data/personal'

export default function Contact(){
 const [status,setStatus]=useState({type:'',message:''}); const [sending,setSending]=useState(false)
 function submit(e){ e.preventDefault(); const form=new FormData(e.currentTarget); const name=String(form.get('name')||'').trim(); const email=String(form.get('email')||'').trim(); const subject=String(form.get('subject')||'').trim(); const message=String(form.get('message')||'').trim(); if(!name||!email||!subject||!message) return setStatus({type:'error',message:'Please complete all fields.'}); if(!/^\S+@\S+\.\S+$/.test(email)) return setStatus({type:'error',message:'Please enter a valid email address.'}); setSending(true); setStatus({type:'',message:''}); setTimeout(()=>{ setSending(false); setStatus({type:'success',message:'Your message has been validated. Connect this form to your preferred email service to send it.'}); e.currentTarget.reset() },700) }
 return <main className="page"><PageMeta title="Contact" description="Get in touch about projects, collaboration, or simply connecting."/><div className="container page-header"><SectionTitle eyebrow="Contact" title="Let’s start a conversation." description="Have a project idea, a school collaboration, or just want to connect? I’d be happy to hear from you."/></div><section className="section pt-0"><div className="container contact-grid"><div className="contact-side"><div className="contact-item"><div className="contact-icon"><Mail size={18}/></div><div><span className="eyebrow">Email</span><a href={`mailto:${personal.email}`}>{personal.email}</a></div></div><div className="contact-item"><div className="contact-icon"><MapPin size={18}/></div><div><span className="eyebrow">Location</span><span>{personal.location}</span></div></div>{personal.github&&<a className="contact-item contact-link" href={personal.github} target="_blank" rel="noreferrer"><div className="contact-icon"><Github size={18}/></div><div><span className="eyebrow">GitHub</span><span>View my code</span></div></a>}{personal.linkedin&&<a className="contact-item contact-link" href={personal.linkedin} target="_blank" rel="noreferrer"><div className="contact-icon"><Linkedin size={18}/></div><div><span className="eyebrow">LinkedIn</span><span>Connect with me</span></div></a>}<div className="contact-note"><strong>Future-ready contact form</strong><p className="muted">The form is intentionally frontend-only for now. Connect it to Formspree, Web3Forms, EmailJS, or your own backend later without exposing private API keys.</p></div></div><form className="contact-form" onSubmit={submit} noValidate><div className="form-grid"><label> Name <input name="name" required placeholder="Your name" autoComplete="name"/></label><label> Email <input name="email" type="email" required placeholder="you@example.com" autoComplete="email"/></label></div><label> Subject <input name="subject" required placeholder="What would you like to talk about?"/></label><label> Message <textarea name="message" required rows="7" placeholder="Write your message here..."></textarea></label>{status.message&&<div className={`form-status ${status.type}`}>{status.message}</div>}<button className="btn btn-primary" type="submit" disabled={sending}>{sending?'Checking…':<>Send message <Send size={17}/></>}</button></form></div></section></main> }
