import { motion } from 'framer-motion'
import { ArrowRight, Github, Linkedin, Mail, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import SectionTitle from '../components/SectionTitle'
import PageMeta from '../components/PageMeta'
import SkillCard from '../components/SkillCard'
import ProjectCard from '../components/ProjectCard'
import { personal } from '../data/personal'
import { skillGroups } from '../data/skills'
import { projects } from '../data/projects'

const fade = { initial:{opacity:0,y:20}, whileInView:{opacity:1,y:0}, viewport:{once:true,amount:.2}, transition:{duration:.55} }
export default function Home(){
 const featured=projects.filter(p=>p.featured).slice(0,3)
 return <main><PageMeta title="Home" description="A BSIT student developer portfolio focused on learning, experimentation, and practical projects."/>
  <section className="hero"><div className="container hero-grid"><motion.div {...fade}><div className="eyebrow"><span className="dot"></span>BSIT student · building and learning</div><h1>{personal.name}<br/><span>{personal.title}</span></h1><p className="hero-copy">{personal.description}</p><div className="hero-actions"><Link className="btn btn-primary" to="/projects">View my projects <ArrowRight size={17}/></Link><Link className="btn btn-secondary" to="/contact">Get in touch <Mail size={17}/></Link></div><div className="socials hero-socials">{personal.github && <a href={personal.github} target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={19}/></a>}{personal.linkedin && <a href={personal.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={19}/></a>}<a href={`mailto:${personal.email}`} aria-label="Email"><Mail size={19}/></a>}</div></motion.div><motion.div className="hero-note" initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} transition={{duration:.6,delay:.1}}><div className="note-grid"></div><div className="note-card"><Sparkles size={18}/><span>Currently exploring</span><strong>Software development · web · databases</strong><p>Learning through small experiments, school work, and projects that turn ideas into something tangible.</p></div></motion.div></div></section>
  <section className="section"><div className="container two-col"><motion.div {...fade}><SectionTitle eyebrow="A little about me" title="Learning by building."/><p className="large-copy">{personal.about}</p><p className="muted">I’m not trying to have every answer yet. I’m focused on building a strong foundation, improving with each project, and discovering which parts of IT I want to go deeper into.</p></motion.div><motion.div {...fade} className="principles"><div><span>01</span><h3>Curious</h3><p className="muted">I like understanding how things work and trying unfamiliar tools.</p></div><div><span>02</span><h3>Hands-on</h3><p className="muted">Projects help me turn concepts from class into practical experience.</p></div><div><span>03</span><h3>Growing</h3><p className="muted">Every project is an opportunity to improve code, problem solving, and design.</p></div></motion.div></div></section>
  <section className="section section-surface"><div className="container"><SectionTitle eyebrow="Toolbox" title="Technologies I’m working with" description="A snapshot of the tools and languages I’m currently learning, practicing, or building with."/><div className="skill-groups">{skillGroups.map(group=><div key={group.title}><h3 className="subheading">{group.title}</h3><div className="skill-grid">{group.items.map((s,i)=><SkillCard key={`${s.name}-${i}`} skill={s}/>)}</div></div>)}</div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Featured work" title="A few things I’ve been building" description="Placeholder projects are included so the structure is ready. Replace them with your real school and personal projects."/><div className="project-grid">{featured.map(p=><ProjectCard key={p.id} project={p} compact/>)}</div><div className="section-cta"><Link className="btn btn-secondary" to="/projects">See all projects <ArrowRight size={17}/></Link></div></div></section>
  <section className="section section-ink"><div className="container learning-grid"><div><span className="eyebrow eyebrow-inverse"><Sparkles size={15}/>Learning journey</span><h2>Still exploring. Still building.</h2></div><div className="learning-list"><p>Exploring different programming paradigms and development workflows.</p><p>Improving web development skills through focused practice.</p><p>Strengthening database and software design fundamentals.</p><p>Using projects to discover the areas of IT I enjoy most.</p></div></div></section>
 </main>
}
